# Generated by Django 4.1.1 on 2022-09-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delimeter',
            name='value',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
