version: "3.9"
services:
  db:
    build:
      context: db_dockerfile
    restart: always
    ports:
      - "54321:5432"

    networks:
      - webnet
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-ocr_engine}

  app:
    build: .
    ports:
      - "8000:8000"
    restart: always
    networks:
      - webnet
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db/${DB_NAME:-ocr_engine}
      DEBUG: ${DEBUG:-False}
      SECRET_KEY: ${SECRET_KEY:-mysupersecretjwtkey}
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

networks:
  webnet:
